### Load in NumPy (remember to pip install numpy first)

In [1]:
import numpy as np

### The Basics

In [129]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [10]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [16]:
# Get Dimension
a.ndim

1

In [18]:
# Get Shape
b.shape

(2, 3)

In [32]:
# Get Type
a.dtype

dtype('int32')

In [31]:
# Get Size
a.itemsize

4

In [29]:
# Get total size
a.nbytes

12

In [139]:
# Get number of elements
a.size

3

### Accessing/Changing specific elements, rows, columns, etc

In [144]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [145]:
# Get a specific element [r, c]
a[1, 5]

13

In [15]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [147]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [26]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [149]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
# Get specific element (work outside in)
b[0,1,1]

4

In [7]:
# replace 
b[:,1,:] = [[9,9],[8,8]]

In [33]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing Different Types of Arrays

In [40]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [44]:
# Any other number
np.full((2,2), 99)

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [49]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [56]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.07805642, 0.53385716],
       [0.02494273, 0.99955252],
       [0.48588042, 0.91247437],
       [0.27779213, 0.16597751]])

In [3]:
# Random Integer values
np.random.randint(-4,2, size=(3,3))

array([[-4,  1,  0],
       [-2, -3, -2],
       [ 0, -4, -2]])

In [76]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [5]:
# Repeat an array
arr = np.array([[1,2,3]])
r = 1
r2 = np.repeat(r,3).reshape(3,1)
r1 = np.repeat(arr,3, axis=0)
print(r2)
print(r1)

[[1]
 [1]
 [1]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [89]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [7]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


### Mathematics

In [111]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [109]:
a + 2

array([5, 6, 7, 8])

In [102]:
a - 2

array([-1,  0,  1,  2])

In [103]:
a * 2

array([2, 4, 6, 8])

In [104]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [118]:
b = np.array([1,0,1,0])
a + b

array([1, 0, 3, 0])

In [113]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [116]:
# Take the sin
np.cos(a)



array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [117]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [160]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [132]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [133]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [134]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [139]:
np.min(stats)

1

In [141]:
np.max(stats, axis=1)

array([3, 6])

In [143]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [161]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [9]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [164]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
##### Load Data from File

In [163]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### Boolean Masking and Advanced Indexing

In [196]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [10]:
e = np.arange(20).reshape((5,4))
e

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [19]:
e[0,1:]

array([1, 2, 3])

In [20]:
e[1:3,0:2]

array([[4, 5],
       [8, 9]])

In [21]:
e[[0,1,2],[1,2,3]]

array([ 1,  6, 11])

In [22]:
e[[0,3,4],2:4]

array([[ 2,  3],
       [14, 15],
       [18, 19]])

In [167]:
a = np.array([1,1,1,-1,1,-1])

b = np.array([[1,2],
              [2,3],
              [3,4],
              [7,8],
              [9,0],
              [7,9]])

result = np.array(np.where(a==-1))
c = b[result,].reshape(result.size,2)
c.shape

(2, 2)

In [88]:
c = 1
a = np.full(3,c).reshape(3,1)
a

array([[1],
       [1],
       [1]])

In [94]:
b= np.zeros(4).reshape(4,1)
b

b

array([[0.],
       [0.],
       [0.],
       [0.]])

In [95]:
np.array([1,2,2])*np.array([1,2,3])

array([1, 4, 6])

In [109]:
t = np.array([1,2,3])
a = t.reshape(3,1)
print(t)
print(a.size)
sum(a)

[1 2 3]
3


array([6])

In [108]:
np.full(3,2).shape

(3,)

In [10]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [11]:
a.reshape((-1,))

array([1, 2, 3, 4])

In [124]:
h = np.where(a>2,True,False)
h

array([False, False,  True,  True])

In [125]:
h.shape

(4,)

In [12]:
x2 = np.arange(0,4.5,0.5)

In [13]:
x2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])